### ISSUE TITLE
"materials" scene cannot extract the mesh out after training on NeuS

### ISSUE THREAD

**Issue by SevenLJY** [bennyguo/instant-nsr-pl#6]
Hi,

Thanks for your great work!

I just noticed that during test time, the "materials" scene cannot export the mesh aftering training on NeuS. Here is the error message:

```
File "/local-scratch/localhome/***/models/geometry.py", line 90, in isosurface
    vmin, vmax = mesh_coarse['v_pos'].amin(dim=0), mesh_coarse['v_pos'].amax(dim=0)
IndexError: amin(): Expected reduction dim 0 to have non-zero size.
```

**Comment by bennyguo** [comment]
Hi! What training config are you using? Did you encounter this problem in the test stage followed automatically after training or you performed the test individually after training? If the latter, make sure you have loaded the pretrained weights using `--resume`, see [https://github.com/bennyguo/instant-nsr-pl#testing](https://github.com/bennyguo/instant-nsr-pl#testing).

Using the default script, I'm able to export the mesh correctly:
<img width="704" alt="image" src="https://user-images.githubusercontent.com/19284678/200154743-ed021621-759e-4099-ab27-d2be22fe9005.png">

**Comment by SevenLJY** [comment]
Thanks for your reply! This problem happens in the test stage following the training automatically (the hotdog case also has this issue). Yet it indeed works well for individual test.

**Comment by bennyguo** [comment]
Well this is weird… In the test stage following training, are novel views rendered correctly? Can you share the training config and the ckpt model?在 2022年11月7日，01:44，SevenLJY ***@***.***> 写道：﻿
Thanks for your reply! This problem happens in the test stage following the training automatically (the hotdog case also has this issue). Yet it indeed works well for individual test.

**Comment by SevenLJY** [comment]
Novel views are rendered correctly (both images and the video). I didn't change any config actually. Here is the parse.yml.
```
name: neus-blender-materials
tag: material
seed: 42
dataset:
  name: blender
  scene: materials
  root_dir: ./load/nerf_synthetic/materials
  img_wh:
  - 800
  - 800
  near_plane: 2.0
  far_plane: 6.0
  white_bkgd: true
  spheric_poses: false
  use_pixel_centers: true
  train_split: train
  val_split: val
  test_split: test
model:
  name: neus
  radius: 1.5
  render_step_size: 0.005
  num_samples_per_ray: 1024
  train_num_rays: 256
  max_train_num_rays: 8192
  grid_prune: true
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 4096
  init_variance: 0.3
  cos_anneal_end: 5000
  geometry:
    name: volume-sdf
    radius: 1.5
    feature_dim: 13
    sdf_activation: none
    sdf_bias: 0.0
    grad_type: analytic
    isosurface:
      method: mc
      resolution: 512
      chunk: 2097152
      threshold: 0.0
    xyz_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378
      include_xyz: true
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      sphere_init: true
      weight_norm: true
  texture:
    name: volume-radiance
    input_feature_dim: 16
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 4
    mlp_network_config:
      otype: FullyFusedMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: sigmoid
system:
  name: neus-system
  resolution: 800
  loss:
    lambda_rgb: 1.0
    lambda_mask: 0.1
    lambda_eikonal: 0.1
  optimizer:
    name: Adam
    args:
      lr: 0.01
      betas:
      - 0.9
      - 0.99
      eps: 1.0e-15
    params:
      geometry:
        lr: 0.01
      texture:
        lr: 0.01
      variance:
        lr: 0.001
  scheduler:
    name: ExponentialLR
    interval: step
    args:
      gamma: 0.9998848773724686
checkpoint:
  save_top_k: -1
  every_n_train_steps: 20000
trainer:
  max_steps: 20000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 10000
  limit_train_batches: 1.0
  limit_val_batches: 0.02
  enable_progress_bar: true
  precision: 16
cmd_args:
  config: configs/neus-blender.yaml
  gpu: '0'
  resume: null
  resume_weights_only: false
  train: true
  validate: false
  test: false
  predict: false
  exp_dir: ./exp
  runs_dir: ./runs
  verbose: false
trial_name: material@20221105-121028
exp_dir: ./exp/neus-blender-materials
save_dir: ./exp/neus-blender-materials/material@20221105-121028/save
ckpt_dir: ./exp/neus-blender-materials/material@20221105-121028/ckpt
code_dir: ./exp/neus-blender-materials/material@20221105-121028/code
config_dir: ./exp/neus-blender-materials/material@20221105-121028/config
```
